# A sample Gemfile
source "https://rubygems.org"

gem 'ipaddress'
gem 'topologygenerator'
gem 'byebug'
gem 'commander'
gem "typhoeus"
gem 'rspec', '~> 3.4'
gem 'spec'
gem 'rspec-mocks' 
gem 'simplecov', :require => false, :group => :test
gem 'colorize'